default_connection_name = "afs"

[connections.afs]
account = "AK31825-EW53848"
user = "NATHANCOHEN"
authenticator = "SNOWFLAKE_JWT"
private_key_path = "C:/snowflake_keys/snowflake_key.p8"
private_key_passphrase = "coker2026"
warehouse = "COMPUTE_WH"
database = "AUDITED_FINANCIALS"
schema = "COMMON"
